///////////////////////////////////////////////////////////
//  ActType.as
//  Macromedia ActionScript Implementation of the Class ActType
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:20
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.action
{
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:20
	 */
	public class ActType
	{
		/**
		 * 循环播放。
		 */
		static public const LOOP: String = "loops";
		
		/**
		 * 停止播放。
		 */
		static public const STOP: String = "stop";
		
		/**
		 * 播放到最后一帧停止。
		 */
		static public const STOP_AT_LAST: String = "stopAtLast";
		
		/**
		 * 播放到最后一帧后停止在第一帧上。
		 */
		static public const STOP_AT_FIRST: String = "stopAtFirst";
		
		/**
		 * 播放到最后一帧后动作跳转到默认动作。
		 */
		static public const PLAY_DEFAULT: String = "playDefault";
		
		/**
		 * 播放到最后一帧后跳转到上一动作。
		 */
		static public const PLAY_LAST: String = "playLast";

	}
}