///////////////////////////////////////////////////////////
//  Actions.as
//  Macromedia ActionScript Implementation of the Class Actions
//  Generated by Enterprise Architect
//  Created on:      30-五月-2009 1:10:46
//  Original author: 陈策
///////////////////////////////////////////////////////////

import qrpg.action.Act;

package qrpg.action
{
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 30-五月-2009 1:10:46
	 */
	public class Actions
	{
	    /**
	     * 动作集。
	     */
	    private var acts: HashMap;

	    /**
	     * 添加动作至动作集。
	     * 
	     * @param act    要添加的动作。
	     */
	    public function addAct(act:Act): void
	    {
	    }

	    /**
	     * 默认动作。
	     */
	    public function get defaultAct(): Act
	    {
	    }

	    /**
	     * 默认动作。
	     * 
	     * @param act
	     */
	    public function set defaultAct(act:Act): void
	    {
	    }

	    /**
	     * 删除动作。
	     * 
	     * @param act    要删除的动作。
	     */
	    public function removeAct(act:Act): Act
	    {
	    }

	    /**
	     * 按动作名删除动作。
	     * 
	     * @param name    要删除的动作的名字。
	     */
	    public function removeActByName(name:String): Act
	    {
	    }

	}//end Actions

}