///////////////////////////////////////////////////////////
//  Frame.as
//  Macromedia ActionScript Implementation of the Class Frame
//  Generated by Enterprise Architect
//  Created on:      30-五月-2009 1:10:47
//  Original author: 陈策
///////////////////////////////////////////////////////////



package qrpg.action
{
	/**
	 * 动作的帧。
	 * @author 陈策
	 * @version 3.0
	 * @created 30-五月-2009 1:10:47
	 */
	public class Frame
	{
	    /**
	     * 该帧的中心点。
	     */
	    public var center: Point;
	    /**
	     * 是否水平翻转。
	     */
	    public var isMirror: Boolean;
	    /**
	     * 该帧在图片中的位置。
	     */
	    public var rect: Rectangle;

	}//end Frame

}