///////////////////////////////////////////////////////////
//  Role.as
//  Macromedia ActionScript Implementation of the Class Role
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:22
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.display
{
	import flash.display.BitmapData;
	import flash.events.Event;
	
	import qrpg.action.Actions;
	import qrpg.core.BmpObject;
	
	/**
	 * 角色类。
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:22
	 */
	public class Role extends BmpObject
	{
		/**
		 * 角色在未加载完成前使用的图片。
		 */
		static public var defaultSource:BitmapData;
		
		/**
		 * 角色在未加载完成前使用的动作。
		 */
		static public var defaultActions:Actions;
		
		private var _realActions:Actions;
		
		/**
		 * 角色类。
		 */		
		public function Role()
		{
			super();
			if ( defaultSource ) source = defaultSource;
			if ( defaultActions ) actions = defaultActions;
		}
		
		/**
		 * 卸载已经加载的资源，节省内存。该方法仅对资源是加载方式提供的实例。
		 */		
		override public function unload():void
		{
			if ( _url )
			{
				if ( actions!=defaultActions ) _realActions = actions;
				_bmpData = defaultSource;
				actions = defaultActions;
				_source = null;
				_isUpdate = true;
				_isLoaded = false;
			}
		}
		
		/**
		 * 加载完成的时候。
		 * @param evt
		 */		
		override protected function onComplete(evt:Event):void
		{
			if ( _realActions ) actions = _realActions;
			super.onComplete(evt);
		}

	}
}