///////////////////////////////////////////////////////////
//  Rander.as
//  Macromedia ActionScript Implementation of the Class Rander
//  Generated by Enterprise Architect
//  Created on:      30-五月-2009 1:10:48
//  Original author: 陈策
///////////////////////////////////////////////////////////



package qrpg.compiler
{
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 30-五月-2009 1:10:48
	 */
	public class Rander
	{
	}//end Rander

}