///////////////////////////////////////////////////////////
//  ISceneAddable.as
//  Macromedia ActionScript Implementation of the Interface ISceneAddable
//  Generated by Enterprise Architect
//  Created on:      30-五月-2009 1:10:47
//  Original author: 陈策
///////////////////////////////////////////////////////////



package qrpg.display
{
	/**
	 * 可以被添加至场景的物体。
	 * @author 陈策
	 * @version 3.0
	 * @created 30-五月-2009 1:10:47
	 */
	public interface ISceneAddable
	{
	    /**
	     * 是否已经加载更新。
	     */
	    public function isLoaded(): Boolean;

	    /**
	     * 是否需要更新。
	     */
	    public function isUpdata(): Boolean;

	}//end ISceneAddable

}