///////////////////////////////////////////////////////////
//  Npc.as
//  Macromedia ActionScript Implementation of the Class Npc
//  Generated by Enterprise Architect
//  Created on:      30-五月-2009 1:10:47
//  Original author: sowawa
///////////////////////////////////////////////////////////

import qrpg.display.Role;

package qrpg.display
{
	/**
	 * @author sowawa
	 * @version 1.0
	 * @created 30-五月-2009 1:10:47
	 */
	public class Npc extends Role
	{
	}//end Npc

}