///////////////////////////////////////////////////////////
//  Npc.as
//  Macromedia ActionScript Implementation of the Class Npc
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:21
//  Original author: sowawa
///////////////////////////////////////////////////////////

package qrpg.display
{
	import qrpg.display.Role;
	
	/**
	 * @author sowawa
	 * @version 1.0
	 * @created 12-六月-2009 22:54:21
	 */
	public class Npc extends Role
	{
	}//end Npc

}