///////////////////////////////////////////////////////////
//  Npc.as
//  Macromedia ActionScript Implementation of the Class Npc
//  Generated by Enterprise Architect
//  Created on:      29-五月-2009 17:51:08
//  Original author: sowawa
///////////////////////////////////////////////////////////

import qrpg.display.Role;

package qrpg.display
{
	/**
	 * @author sowawa
	 * @version 1.0
	 * @created 29-五月-2009 17:51:08
	 */
	public class Npc extends Role
	{
	}//end Npc

}