///////////////////////////////////////////////////////////
//  Role.as
//  Macromedia ActionScript Implementation of the Class Role
//  Generated by Enterprise Architect
//  Created on:      29-五月-2009 17:51:08
//  Original author: 陈策
///////////////////////////////////////////////////////////

import qrpg.display.ISceneAddable;
import qrpg.display.IBmpObject;
import qrpg.core.BmpObject;

package qrpg.display
{
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 29-五月-2009 17:51:08
	 */
	public class Role extends BmpObject implements ISceneAddable, IBmpObject
	{
	    /**
	     * 是否需要更新。
	     */
	    public function isUpdata(): Boolean
	    {
	    }

	    /**
	     * 是否已经加载更新。
	     */
	    public function isLoaded(): Boolean
	    {
	    }

	    /**
	     * 位图显示物体显示的数据。
	     * 
	     * @param rect    要显示的图片区域。如果为null，则按默认的显示区域显示。
	     */
	    public function displayData(rect:Rectangle): BitmapData
	    {
	    }

	    /**
	     * 代表显示区域的矩形。
	     */
	    public function displayRect(): Rectangle
	    {
	    }

	}//end Role

}