///////////////////////////////////////////////////////////
//  LayerMain.as
//  Macromedia ActionScript Implementation of the Class LayerMain
//  Generated by Enterprise Architect
//  Created on:      29-五月-2009 17:51:07
//  Original author: 陈策
///////////////////////////////////////////////////////////

import qrpg.display.ObjectGroup;

package qrpg.scene
{
	/**
	 * 场景的主要层。里边放置所有有前后关系的图层。
	 * @author 陈策
	 * @version 3.0
	 * @created 29-五月-2009 17:51:07
	 */
	public class LayerMain extends ObjectGroup
	{
	}//end LayerMain

}