///////////////////////////////////////////////////////////
//  RPGScene.as
//  Macromedia ActionScript Implementation of the Class RPGScene
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:22
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.scene
{
	import qrpg.scene.Scene;
	
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:22
	 */
	public class RPGScene extends Scene
	{
	}//end RPGScene

}