///////////////////////////////////////////////////////////
//  RPGScene.as
//  Macromedia ActionScript Implementation of the Class RPGScene
//  Generated by Enterprise Architect
//  Created on:      30-五月-2009 1:10:48
//  Original author: 陈策
///////////////////////////////////////////////////////////

import qrpg.scene.Scene;

package qrpg.scene
{
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 30-五月-2009 1:10:48
	 */
	public class RPGScene extends Scene
	{
	}//end RPGScene

}