///////////////////////////////////////////////////////////
//  Scene.as
//  Macromedia ActionScript Implementation of the Class Scene
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:22
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.scene
{
	import flash.display.Bitmap;
	import flash.geom.Rectangle;
	
	import qrpg.core.DisplayGameObject;
	import qrpg.display.ISceneAddable;
	
	/**
	 * 场景的基类。
	 * 主要处理场景及场景内物体的显示。场景分为四层：背景块，背景层，中间层，前层层。
	 * 背景块是由若干小块组成的。
	 * 背景层是放始终在角色之下的物体的图层。该图层不可以被点击。
	 * 中间层是角色和与角色有可能发生前后关系的图层。
	 * 前景层是放始终在角色之上的物体的图层。该图层不可以被点击。
	 * 
	 * 该类的所有鼠标事件都会被中止，不向上传递。场景里的所有鼠标事件均重新发布。
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:22
	 */
	public class Scene extends DisplayGameObject
	{
		/**
		 * 场景里分块加载的背景。
		 */
		internal var backGround: SceneBackGround;
		/**
		 * 场景背景。
		 */
		internal var layerBackGround: ObjectGroup;
		/**
		 * 场景前景。
		 */
		internal var layerFront: ObjectGroup;
		/**
		 * 场景的主要层。
		 */
		internal var layerMain: LayerMain;
	
		/**
		 * 向背景添加物体。
		 * return 返回目前背景有多少个物体。
		 * 
		 * @param bg向背景添加的物体。
		 */
		public function addBackGround(bg:ISceneAddable): int
		{
			return 0;
		}
	
		/**
		 * 向背景添加物体。
		 * return 返回目前背景有多少个物体。
		 * 
		 * @param bg向背景添加的物体。
		 * @param index添加至指定的位置。
		 */
		public function addBackGroundAt(bg:ISceneAddable, index:int): int
		{
			return 0;
		}
	
		/**
		 * 添加前景物体。
		 * 
		 * @param obj要添加的物体。
		 */
		public function addFront(obj:ISceneAddable): int
		{
			return 0;
		}
	
		/**
		 * 添加前景物体至指定位置。
		 * 
		 * @param obj要添加的物体。
		 * @param index指定的位置。
		 */
		public function addFrontAt(obj:ISceneAddable, index:int): int
		{
			return 0;
		}
	
		/**
		 * 添加中间层物体。
		 * 
		 * @param obj要添加的物体。
		 */
		public function addMain(obj:ISceneAddable): int
		{
			return 0;
		}
	
		/**
		 * 添加中间层物体至指定位置。
		 * 
		 * @param obj要添加的物体。
		 * @param index指定的位置。
		 */
		public function addMainAt(obj:ISceneAddable, index:int): int
		{
			return 0;
		}
	
		/**
		 * 加载场景。
		 */
		public function load(): void
		{
		}
	
		/**
		 * 场景的高。
		 */
		public function get sceneHeight(): Number
		{
			return 0;
		}
	
		/**
		 * 场景的高。
		 * 
		 * @param width
		 */
		public function set sceneHeight(width:Number): void
		{
		}
	
		/**
		 * 场景的宽。
		 */
		public function get sceneWidth(): Number
		{
			return 0
		}
	
		/**
		 * 场景的宽。
		 * 
		 * @param width
		 */
		public function set sceneWidth(width:Number): void
		{
		}
	
		/**
		 * 设置代表显示区域的矩形。
		 * 
		 * @param rect代表显示区域的矩形。
		 */
		public function screenRect(rect:Rectangle): void
		{
		}

	}
}