///////////////////////////////////////////////////////////
//  SceneBackGround.as
//  Macromedia ActionScript Implementation of the Class SceneBackGround
//  Generated by Enterprise Architect
//  Created on:      29-五月-2009 17:51:08
//  Original author: 陈策
///////////////////////////////////////////////////////////

import qrpg.display.ObjectGroup;

package qrpg.scene
{
	/**
	 * 场景背景。
	 * @author 陈策
	 * @version 3.0
	 * @created 29-五月-2009 17:51:08
	 */
	public class SceneBackGround extends ObjectGroup
	{
	}//end SceneBackGround

}