///////////////////////////////////////////////////////////
//  Building.as
//  Macromedia ActionScript Implementation of the Class Building
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:20
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.display
{
	import flash.display.BitmapData;
	import flash.geom.Rectangle;
	
	import qrpg.core.BmpObject;
	
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:20
	 */
	public class Building extends BmpObject
	{
		/**
		 * 得到显示的BitmapData
		 * 
		 * @param rect    显示的区域。如果不设定的话，则按默认的显示区域来显示。
		 */
		override public function displayData(cut:Boolean=false) : BitmapData
		{
			super.displayData(cut);
			return null;
		}

		/**
		 * 代表默认显示区域的矩形。
		 */
		override public function get displayRect(): Rectangle
		{
			return null;
		}

	}//end Building

}