///////////////////////////////////////////////////////////
//  GameMouseEvent.as
//  Macromedia ActionScript Implementation of the Class GameMouseEvent
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:21
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.event
{
	import qrpg.event.GameEvent;
	
	/**
	 * 游戏里的鼠标事件。
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:21
	 */
	public class GameMouseEvent extends GameEvent
	{
		public function GameMouseEvent(type:String, bubbles:Boolean=false, cancelable:Boolean=false)
		{
			super(type, bubbles, cancelable);
		}
	}
}