///////////////////////////////////////////////////////////
//  GameEvent.as
//  Macromedia ActionScript Implementation of the Class GameEvent
//  Generated by Enterprise Architect
//  Created on:      30-五月-2009 1:10:47
//  Original author: 陈策
///////////////////////////////////////////////////////////



package qrpg.event
{
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 30-五月-2009 1:10:47
	 */
	public class GameEvent extends Event
	{
	    /**
	     * 发布全局事件。
	     */
	    public function dispatch(): void
	    {
	    }

	}//end GameEvent

}