///////////////////////////////////////////////////////////
//  GameMouseEvent.as
//  Macromedia ActionScript Implementation of the Class GameMouseEvent
//  Generated by Enterprise Architect
//  Created on:      30-五月-2009 1:10:47
//  Original author: 陈策
///////////////////////////////////////////////////////////

import qrpg.event.GameEvent;

package qrpg.event
{
	/**
	 * 游戏里的鼠标事件。
	 * @author 陈策
	 * @version 3.0
	 * @created 30-五月-2009 1:10:47
	 */
	public class GameMouseEvent extends GameEvent
	{
	}//end GameMouseEvent

}