///////////////////////////////////////////////////////////
//  LayerMain.as
//  Macromedia ActionScript Implementation of the Class LayerMain
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:21
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.scene
{
	import qrpg.scene.ObjectGroup;
	
	/**
	 * 场景的主要层。里边放置所有有前后关系的图层。
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:21
	 */
	public class LayerMain extends ObjectGroup
	{
	}//end LayerMain

}