///////////////////////////////////////////////////////////
//  SceneBackGround.as
//  Macromedia ActionScript Implementation of the Class SceneBackGround
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:22
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.scene
{
	import qrpg.scene.ObjectGroup;
	
	/**
	 * 场景背景。
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:22
	 */
	public class SceneBackGround extends ObjectGroup
	{
	}//end SceneBackGround

}