///////////////////////////////////////////////////////////
//  RPGScene.as
//  Macromedia ActionScript Implementation of the Class RPGScene
//  Generated by Enterprise Architect
//  Created on:      29-五月-2009 16:58:54
//  Original author: 陈策
///////////////////////////////////////////////////////////

import qrpg.scene.Scene;

package qrpg.scene
{
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 29-五月-2009 16:58:54
	 */
	public class RPGScene extends Scene
	{
	}//end RPGScene

}