///////////////////////////////////////////////////////////
//  BmpData.as
//  Macromedia ActionScript Implementation of the Class BmpData
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:20
//  Original author: 陈策
///////////////////////////////////////////////////////////

package qrpg.pathfinding
{
	import qrpg.pathfinding.IAStarData;
	
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:20
	 */
	public class BmpData implements IAStarData
	{
		/**
		 * 该点是否可以通过。
		 * 
		 * @param pxX座标。
		 * @param pyY座标。
		 */
		public function isBlock(px:int, py:int): Boolean
		{
			return false;
		}

	}
}