///////////////////////////////////////////////////////////
//  IAStarData.as
//  Macromedia ActionScript Implementation of the Interface IAStarData
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:21
//  Original author: 陈策
///////////////////////////////////////////////////////////



package qrpg.pathfinding
{
	/**
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:21
	 */
	public interface IAStarData
	{
	    /**
	     * 该点是否可以通过。
	     * 
	     * @param px    X座标。
	     * @param py    Y座标。
	     */
	    function isBlock(px:int, py:int): Boolean;

	}//end IAStarData

}