///////////////////////////////////////////////////////////
//  AStar.as
//  Macromedia ActionScript Implementation of the Class AStar
//  Generated by Enterprise Architect
//  Created on:      12-六月-2009 22:54:20
//  Original author: 陈策
///////////////////////////////////////////////////////////



package qrpg.pathfinding
{
	/**
	 * A星寻路。
	 * @author 陈策
	 * @version 3.0
	 * @created 12-六月-2009 22:54:20
	 */
	public class AStar
	{
		/**
		 * 寻路。
		 * 
		 * @param startX起点X座标。
		 * @param startY起点Y座标。
		 * @param endX终点X座标。
		 * @param endY终点Y座标。
		 */
		public function find(startX:int, startY:int, endX:int, endY:int): Array
		{
			return null;
		}

	}
}