///////////////////////////////////////////////////////////
//  BmpObject.as
//  Macromedia ActionScript Implementation of the Class BmpObject
//  Generated by Enterprise Architect
//  Created on:      29-五月-2009 17:51:07
//  Original author: 陈策
///////////////////////////////////////////////////////////



package qrpg.core
{
	/**
	 * 显示物体的基类。
	 * 该类不是DisplayObject的子类，所以是不可以添加至显示列表里的。要显示该类的实例，需要用该类的displayData()方法得到需要显示的图像的Bit
	 * mapData。
	 * @author 陈策
	 * @version 3.0
	 * @created 29-五月-2009 17:51:07
	 */
	public class BmpObject extends EventDispatcher
	{
	    /**
	     * 显示的图片数据。
	     * 
	     * @param rect    要显示的矩形。
	     */
	    public function displayData(rect:Rectangle = null): BitmapData
	    {
	    }

	    /**
	     * 显示区域。
	     */
	    public function get displayRect(): Rectangle
	    {
	    }

	}//end BmpObject

}